# Generated by Django 4.1.7 on 2023-12-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('gender', models.CharField(max_length=4)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('District', models.CharField(max_length=100)),
                ('Branches', models.CharField(max_length=100)),
                ('Account_type', models.CharField(max_length=10)),
                ('Material', models.CharField(max_length=100)),
            ],
        ),
    ]
