# Generated by Django 4.1.7 on 2023-12-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='phone',
            new_name='Phone',
        ),
    ]
