# Generated by Django 4.1.7 on 2023-12-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_rename_name_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
