# Generated by Django 4.1.7 on 2023-12-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
