# Generated by Django 4.1.7 on 2023-12-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_form_age_alter_form_email_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Branches',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='District',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
