# Generated by Django 4.1.7 on 2023-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_form_branches_alter_form_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Account_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
