# Generated by Django 4.1.7 on 2023-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_form_account_type_alter_form_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
