# Generated by Django 4.1.7 on 2023-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Age',
            field=models.IntegerField(default=456),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
