# Generated by Django 4.1.7 on 2023-12-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_form_age_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(default='exit', max_length=8),
            preserve_default=False,
        ),
    ]
