# Generated by Django 4.1.7 on 2023-12-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_alter_form_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
